version: '3'
services:
  postgres:
    image: postgres:alpine
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:
